[lint.per-file-ignores]
"core_app.py" = ["E402"]
"crawler.py" = ["E402"]
"deep_scrape.py" = ["E402"]
"functii.py" = ["E402"]
"main.py" = ["E402"]
"scrape_eclass.py" = ["E402"]
"scrape_glc.py" = ["E402"]
"start_crawler.py" = ["E402"]
"deep_scrape_v2.py" = ["E402"]
